Clientnewsletter:
    type: entity
    table: clientnewsletter
    fields:
        idClientnewsletter:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_clientnewsletter
            generator:
                strategy: IDENTITY
        actifClientNewsletter:
            type: integer
            unsigned: false
            nullable: false
            column: actif_client_newsletter
        emailClientnewsletter:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: email_clientnewsletter
    manyToOne:
        isoLangue:
            targetEntity: Langue
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                iso_langue:
                    referencedColumnName: iso_langue
            orphanRemoval: false
        idProjet:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_projet:
                    referencedColumnName: id_projet
            orphanRemoval: false
    lifecycleCallbacks: {  }
