Gallerie:
    type: entity
    table: gallerie
    fields:
        idGallerie:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_gallerie
            generator:
                strategy: IDENTITY
    manyToMany:
        isoLangue:
            targetEntity: Langue
            cascade: {  }
            mappedBy: null
            inversedBy: idGallerie
            joinTable:
                name: gallerielangue
                joinColumns:
                    -
                        name: id_gallerie
                        referencedColumnName: id_gallerie
                inverseJoinColumns:
                    -
                        name: iso_langue
                        referencedColumnName: iso_langue
            orderBy: null
        idPage:
            targetEntity: Page
            cascade: {  }
            mappedBy: null
            inversedBy: idGallerie
            joinTable:
                name: galleriepage
                joinColumns:
                    -
                        name: id_gallerie
                        referencedColumnName: id_gallerie
                inverseJoinColumns:
                    -
                        name: id_page
                        referencedColumnName: id_page
            orderBy: null
    manyToOne:
        idProjet:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_projet:
                    referencedColumnName: id_projet
            orphanRemoval: false
    lifecycleCallbacks: {  }
