Projet:
    type: entity
    table: projet
    fields:
        idProjet:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_projet
            generator:
                strategy: IDENTITY
        nomProjet:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: nom_projet
        userProjet:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: user_projet
        passProjet:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: pass_projet
        analyticsProjet:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: analytics_projet
        maintenanceProjet:
            type: integer
            unsigned: false
            nullable: false
            column: maintenance_projet
        dateproductionProjet:
            type: datetime
            nullable: false
            column: dateproduction_projet
        dateProjet:
            type: datetime
            nullable: false
            column: date_projet
        lattitudeProjet:
            type: integer
            unsigned: false
            nullable: true
            column: lattitude_projet
        longitudeProjet:
            type: integer
            unsigned: false
            nullable: true
            column: longitude_projet
        urlproductionProjet:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: urlproduction_projet
    manyToMany:
        idAdmin:
            targetEntity: Admin
            cascade: {  }
            mappedBy: idProjet
            inversedBy: null
            joinTable: null
            orderBy: null
        isoLangue:
            targetEntity: Langue
            cascade: {  }
            mappedBy: null
            inversedBy: idProjet
            joinTable:
                name: languesite
                joinColumns:
                    -
                        name: id_projet
                        referencedColumnName: id_projet
                inverseJoinColumns:
                    -
                        name: iso_langue
                        referencedColumnName: iso_langue
            orderBy: null
    manyToOne:
        idClient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id_client
            orphanRemoval: false
        idActualite:
            targetEntity: Actualite
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_actualite:
                    referencedColumnName: id_actualite
            orphanRemoval: false
        idEtatprojet:
            targetEntity: Etatprojet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_etatprojet:
                    referencedColumnName: id_etatprojet
            orphanRemoval: false
    lifecycleCallbacks: {  }
