Typepage:
    type: entity
    table: typepage
    fields:
        idTypepage:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_typepage
            generator:
                strategy: IDENTITY
        nomTypepage:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: nom_typepage
    lifecycleCallbacks: {  }
