parameters:
#    admin_admin.example.class: Admin\AdminBundle\Example

services:
#    admin_admin.example:
#        class: %admin_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
