Admin\AdminBundle\Entity\Actualite:
    type: entity
    table: actualite
    fields:
        idActualite:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_actualite
            generator:
                strategy: IDENTITY
        dateActualite:
            type: datetime
            nullable: false
            column: date_actualite
    manyToMany:
        isoLangue:
            targetEntity: Langue
            cascade: {  }
            mappedBy: null
            inversedBy: idActualite
            joinTable:
                name: actulangue
                joinColumns:
                    -
                        name: id_actualite
                        referencedColumnName: id_actualite
                inverseJoinColumns:
                    -
                        name: iso_langue
                        referencedColumnName: iso_langue
            orderBy: null
    lifecycleCallbacks: {  }
