Admin\AdminBundle\Entity\Email:
    type: entity
    table: email
    fields:
        idEmail:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_email
            generator:
                strategy: IDENTITY
        adresseEmail:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: adresse_email
        defaultEmail:
            type: integer
            unsigned: false
            nullable: false
            column: default_email
    manyToOne:
        idProjet:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_projet:
                    referencedColumnName: id_projet
            orphanRemoval: false
    lifecycleCallbacks: {  }
