Admin\AdminBundle\Entity\Newsletter:
    type: entity
    table: newsletter
    fields:
        idNewsletter:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_newsletter
            generator:
                strategy: IDENTITY
        sujetNewsletter:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: sujet_newsletter
        bodyNewsletter:
            type: text
            nullable: false
            column: body_newsletter
        dateNewsletter:
            type: datetime
            nullable: false
            column: date_newsletter
    manyToOne:
        idProjet:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_projet:
                    referencedColumnName: id_projet
            orphanRemoval: false
    lifecycleCallbacks: {  }
