Admin\AdminBundle\Entity\Sujet:
    type: entity
    table: sujet
    fields:
        idSujet:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_sujet
            generator:
                strategy: IDENTITY
        titreSujet:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: titre_sujet
        dateSujet:
            type: datetime
            nullable: false
            column: date_sujet
        actifSujet:
            type: integer
            unsigned: false
            nullable: true
            column: actif_sujet
    manyToOne:
        idProjet:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_projet:
                    referencedColumnName: id_projet
            orphanRemoval: false
        idAdmin:
            targetEntity: Admin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_admin:
                    referencedColumnName: id_admin
            orphanRemoval: false
        idClient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id_client
            orphanRemoval: false
    lifecycleCallbacks: {  }
