Admin\AdminBundle\Entity\Typeadmin:
    type: entity
    table: typeadmin
    fields:
        idTypeadmin:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_typeadmin
            generator:
                strategy: IDENTITY
        libelleTypeadmin:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: libelle_typeadmin
    lifecycleCallbacks: {  }
