<?php

namespace Admin\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class IndexController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Admin\AdminBundle\Controller\IndexController();
        return $instance;
    }
}
